### ISSUE TITLE
[DOC] Documento de visão

### ISSUE THREAD

**Issue by caiooliv** [driblo-desenho-de-software-2019-2/docs#12]
### Descrição:
Criação do documento de visão, para melhor entendimento do projeto.

### Tópicos do documento
Lista de tarefas para serem realizadas. 

- [x] Documento de visão

**Comment by byronkamal** [comment]
template para doc de visão https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_6.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

**Comment by caiooliv** [comment]
Documento de visão entregue e adicionado nos pages.
