### ISSUE TITLE
[DOC] Priorização do backlog

### ISSUE THREAD

**Issue by caiooliv** [driblo-desenho-de-software-2019-2/docs#13]
### Descrição:
Deve ser criado o documento no pages, além da priorização dos requisitos levantados.

### Tópicos do documento
Lista de tarefas para serem realizadas. 

- [x] Documento do backlog no pages.
- [x] MoSCoW
- [x] First things first
 
### Comentários
Alguma informação necessária para melhor compreensão.

**Comment by matheus-rn** [comment]
O product backlog foi criado e priorizado usando as técnicas MOSCOW e First Things First.
