### ISSUE TITLE
[TS] Configuração de ambiente Frontend

### ISSUE THREAD

**Issue by caiooliv** [driblo-desenho-de-software-2019-2/docs#28]
### Descrição:
Deve ser configurado as ferramentas utilizadas para o desenvolvimento do frontend do projeto.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Definição e configuração das ferramentas do ambiente de frontend

 
### Comentários
Uso da ferramenta [Solidairity](https://infinitered.github.io/solidarity/#/) recomendado

**Comment by matheus-rn** [comment]
O ambiente para o desenvolvimento do frontend foi configurado.
