### ISSUE TITLE
[TS] Configuração de ambiente Backend

### ISSUE THREAD

**Issue by caiooliv** [driblo-desenho-de-software-2019-2/docs#29]
### Descrição:
Deve ser configurado as ferramentas utilizadas para o desenvolvimento do frontend do projeto.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Criação de repositórios dos microserviços
- [x]  Definição e configuração das ferramentas do ambiente de frontend

**Comment by matheus-rn** [comment]
O ambiente do backend foi configurado.
