### ISSUE TITLE
[US] Criar API da Pelada

### ISSUE THREAD

**Issue by jpmota2208** [driblo-desenho-de-software-2019-2/docs#34]
### Descrição:
Início do cadastro da pelada no sistema.

### Tarefas
Lista de tarefas para serem realizadas. 

- [x] Criar pelada
- [x] Criar usuário
- [x] Relacionar pelada com usuário
- [x] Criar controle dos times
- [x] Criar controle dos gols

**Comment by matheus-rn** [comment]
Os controles de pelada, usuário, times e gols foram implementados.
